services:
  frontend:
    image: ${FRONTEND_IMAGE}:${FRONTEND_TAG}
    restart: unless-stopped
    networks:
      - market_network

  backend:
    image: ${BACKEND_IMAGE}:${BACKEND_TAG}
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=local
    networks:
      - market_network

  reverse-proxy:
    image: ${REVERSE_PROXY_IMAGE}:${REVERSE_PROXY_TAG}
    restart: unless-stopped
    networks:
      - market_network
      - ${GATEWAY_NETWORK}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.market.rule=Host(`${GATEWAY_DOMAIN}`)"
      - "traefik.http.routers.market.entrypoints=web,websecure"
      - "traefik.http.routers.market.tls.certresolver=myresolver"

networks:
  market_network:
    driver: bridge
  ${GATEWAY_NETWORK}:
    external: true
