name: build-reverse-proxy

on:
  push:
    branches: [ master ]
    paths:
      - "reverse-proxy/**"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Set image name
#        run: |
#          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/market-reverse-proxy
#          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> $GITHUB_ENV

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

#      - name: Build and push
#        uses: docker/build-push-action@v6
#        with:
#          context: ./reverse-proxy
#          push: true
#          tags: |
#            ${{ env.IMAGE_NAME }}:latest
#            ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
            
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          dockerfile: ./reverse-proxy/Dockerfile
          context: ./reverse-proxy
          image_tag: ${{ env.SHORT_SHA }}
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.INFRA_TOKEN }}

      - name: Trigger infra update
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.INFRA_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/daureslaurent/Market-Infra/dispatches \
            -d '{
              "event_type": "update-reverse",
              "client_payload": {
                "image": "'"${{ github.repository }}"'",
                "tag": "'"${{ env.SHORT_SHA }}"'"
              }
            }'
