name: light-deploy.yml
on:
  repository_dispatch:
    types: [ deploy ]
#  push:
#    branches: [ deploy-bot ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/deployuser
            if [ ! -d "infra/.git" ]; then
              git clone -b https://github.com/daureslaurent/Market-Infra.git infra
            fi
            cd infra
            git fetch --all
            git reset --hard origin/main
            git clean -fd
            cd light-deploy
            docker compose --env-file versions.env down
            docker compose --env-file versions.env pull
            docker compose --env-file versions.env up -d